{% set name = "tike" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomography/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6cef2d284bb1a74301a31a81134707faf29fd27408d1e20cd13ca9be036c9ce7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm_git_archive
  run:
    - cupy >=8
    - importlib_metadata # backport for python<3.8
    - importlib_resources # backport for python<3.9
    - numpy >=1.17
    - matplotlib-base
    - mpi4py >=3
    - python >=3.6
    - py-opencv
    - scipy
    - setuptools >=45

test:
  imports:
  # Cannot import any module that contains CuPy
    - tike
#     - tike.align
#     - tike.communicators
#     - tike.lamino
#     - tike.ptycho
    - tike.linalg
    - tike.opt
#     - tike.random
    - tike.scan
    - tike.trajectory
    - tike.view

about:
  home: https://github.com/tomography/tike
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Tike is a toolbox for tomographic reconstruction of 3D objects from
    ptychography data.
  description: |
    The aim of Tike is to provide fast and accurate implementations of a wide
    variety of reconstruction algorithms, and to provide a common platform for
    the synchrotron research community.
  doc_url: https://tike.readthedocs.io/
  dev_url: https://github.com/tomography/tike

extra:
  recipe-maintainers:
    - carterbox
