{% set name = "tike" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomography/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2ed0c2b8157438113544c290b7af7868a1bc5f298b1988645373868484c90f1d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm_git_archive
  run:
    - cupy >=7
    - importlib_resources
    - numpy >=1.17
    - matplotlib-base
    - mpi4py
    - python >=3.6
    - py-opencv
    - scipy
    - setuptools

test:
  imports:
    - tike
    - tike.scan
    - tike.trajectory

about:
  home: https://github.com/tomography/tike
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Tike is a toolbox for tomographic reconstruction of 3D objects from
    ptychography data.
  description: |
    The aim of Tike is to provide fast and accurate implementations of a wide
    variety of reconstruction algorithms, and to provide a common platform for
    the synchrotron research community.
  doc_url: https://tike.readthedocs.io/
  dev_url: https://github.com/tomography/tike

extra:
  recipe-maintainers:
    - carterbox
