{% set name = "tike" %}
{% set version = "0.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AdvancedPhotonSource/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 61a5ae67bd06cdeaada013002c86c7adfd2df7dedbaf715784ae21fbb6d91ed4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=6.2
    - setuptools_scm_git_archive
  run:
    - cupy >=8,!=10.3.0
    - importlib_metadata # backport for python<3.8
    - importlib_resources # backport for python<3.9
    - matplotlib-base =3.*
    - mpi4py =3.*
    - numpy >=1.17,<2
    - python >=3.6
    - py-opencv >=3.4,<5
    - scipy =1.*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
  # Cannot import any module that contains CuPy
    - tike
#     - tike.align
#     - tike.communicators
#     - tike.lamino
#     - tike.ptycho
    - tike.linalg
    - tike.opt
#     - tike.random
    - tike.scan
    - tike.trajectory
    - tike.view

about:
  home: https://github.com/AdvancedPhotonSource/tike
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Tike is a toolbox for tomographic reconstruction of 3D objects from
    ptychography data.
  description: |
    The aim of Tike is to provide fast and accurate implementations of a wide
    variety of reconstruction algorithms, and to provide a common platform for
    the synchrotron research community.
  doc_url: https://tike.readthedocs.io/
  dev_url: https://github.com/AdvancedPhotonSource/tike

extra:
  recipe-maintainers:
    - carterbox
